### ISSUE TITLE
Better README

### ISSUE THREAD

**Issue by monuelo** [monuelo/i-just-want-to-play-tetris#13]
## Description

We could have a rich README.md with badges, instructions to run, contribute, and play.

**Comment by c-grigsby** [comment]
I updated the README.md to include the description above and added CONTRIBUTE.md to the forked repo at 

https://github.com/c-grigsby/i-just-want-to-play-tetris/tree/chore/app-maintenance

Let me know if there is anything else you want there, or to be modified before making a PR
Note: A link to the CONTRIBUTE.md file won't work until the branch is merged to master 
Thanks!

**Comment by monuelo** [comment]
Oh, Nice. Just a few adjustments: 
- Rename `CONTRIBUTE.md` to `CONTRIBUTING.md`
- I believe we don't need bullet points and dividers in sections that only have a small description
- Remove the duplicated URL
- You can use [this project](https://github.com/monuelo/cast-sh) as reference

**Comment by monuelo** [comment]
Closed by #20
