### ISSUE TITLE
Add option to mute music

### ISSUE THREAD

**Issue by monuelo** [monuelo/i-just-want-to-play-tetris#14]
## Description

It would be great to have a command to mute the music. Not everyone wants to play with a loud song.

**Comment by c-grigsby** [comment]
Greetings! Cool project, would you like pull requests for issues to made directly to the master branch? I don't see a develop branch kicking around yet. Thanks!

**Comment by monuelo** [comment]
Hey @c-grigsby! Glad you liked it 🥳 
Yes, let's use the master branch for now. I'll consider create a dev branch too, thanks!

**Comment by monuelo** [comment]
Actually, I'm going to create a new dev branch, is that ok for you?

**Comment by monuelo** [comment]
Well, [the branch](https://github.com/monuelo/i-just-want-to-play-tetris/tree/dev) came very quickly. 🚀

**Comment by c-grigsby** [comment]
Nice! We'd get to Mars in no time if everything worked out that fast. haha I'm taking a look at how you put things together in the app now.
